
name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout common build repo
      uses: actions/checkout@v4
      with:
        repository: orppst/build-logic
        path: build-logic
        
    - name: Checkout this  repo
      uses: actions/checkout@v4
      with:
          path: main

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-root-directory: main
        cache-disabled: true
        cache-overwrite-existing: true
        
    - name: Build with Gradle Wrapper
      working-directory: ./main
      run: ./gradlew build

